import React from 'react';
import type { CustomerPortfolioClientSnapshot } from '../../core/customerSuccess/CustomerPortfolioTypes';

export default function CustomerRiskTable({ snapshots }: { snapshots: CustomerPortfolioClientSnapshot[] }) {
  return <section className="rounded-2xl border border-[var(--border-color)] bg-[var(--bg-card)] overflow-hidden"><div className="p-5 border-b border-[var(--border-color)]"><span className="text-[10px] uppercase font-mono tracking-[0.22em] text-[var(--text-secondary)] font-black">Mapa de risco</span><h2 className="text-lg font-black text-[var(--text-main)] mt-1">Carteira por saúde e potencial</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="bg-white/5 text-[10px] uppercase tracking-widest text-[var(--text-secondary)]"><tr><th className="text-left px-4 py-3">Cliente</th><th className="text-left px-4 py-3">Risco</th><th className="text-left px-4 py-3">Saúde</th><th className="text-left px-4 py-3">Implantação</th><th className="text-left px-4 py-3">Chamados</th><th className="text-left px-4 py-3">Receita mensal</th><th className="text-left px-4 py-3">Expansão</th></tr></thead><tbody>{snapshots.slice(0, 10).map((item) => <tr key={item.clientId} className="border-t border-[var(--border-color)]"><td className="px-4 py-4"><strong className="text-[var(--text-main)]">{item.clientName}</strong><span className="block text-[10px] text-[var(--text-secondary)] mt-1">{[item.city, item.state].filter(Boolean).join(' / ') || 'Localidade não informada'}</span></td><td className="px-4 py-4"><span className={`rounded-full px-2 py-1 text-[10px] font-black uppercase ${riskClass(item.riskLevel)}`}>{item.riskLevel}</span><span className="block text-[10px] text-[var(--text-secondary)] mt-2">{item.reasons[0]}</span></td><td className="px-4 py-4 font-black text-[var(--text-main)]">{item.healthScore}%</td><td className="px-4 py-4">{item.implementationProgress}%</td><td className="px-4 py-4">{item.openTickets}</td><td className="px-4 py-4">{formatCurrency(item.recurringRevenue)}</td><td className="px-4 py-4 font-black text-emerald-300">{item.expansionPotential}%</td></tr>)}</tbody></table></div></section>;
}

function riskClass(level: CustomerPortfolioClientSnapshot['riskLevel']) { if (level === 'crítico') return 'bg-red-500/15 text-red-300'; if (level === 'atenção') return 'bg-amber-500/15 text-amber-300'; return 'bg-emerald-500/15 text-emerald-300'; }
function formatCurrency(value: number) { return new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL', maximumFractionDigits: 0 }).format(value || 0); }
