import React, { useState } from 'react';
import { ArrowRight, CheckCircle2, ListChecks } from 'lucide-react';
import type { ExecutiveReportAlert } from '../../core/reports/ExecutiveReportTypes';

export default function ExecutiveReportAlerts({ alerts, existingTaskTitles, onCreateTask, onNavigate }: { alerts: ExecutiveReportAlert[]; existingTaskTitles: Set<string>; onCreateTask: (title: string) => Promise<void>; onNavigate: (tab: string) => void; }) {
  const [creating, setCreating] = useState<string | null>(null);
  if (!alerts.length) return <div className="rounded-2xl border border-emerald-500/30 bg-emerald-500/5 p-5 flex gap-3"><CheckCircle2 className="w-5 h-5 text-emerald-500"/><div><h4 className="font-bold text-[var(--text-main)]">Nenhum alerta executivo crítico</h4><p className="text-sm text-[var(--text-secondary)]">Os indicadores consolidados estão dentro da faixa saudável.</p></div></div>;
  return <div className="rounded-2xl border border-[var(--border-color)] bg-[var(--bg-card)] p-5"><div className="flex items-center gap-2 mb-4"><ListChecks className="w-5 h-5 text-[var(--blue-accent)]"/><h4 className="font-extrabold text-[var(--text-main)]">Plano de ação do relatório</h4></div><div className="space-y-3">{alerts.map((alert) => { const exists = existingTaskTitles.has(alert.taskTitle.toLowerCase()); return <div key={alert.id} className="rounded-xl border border-[var(--border-color)] p-4 flex flex-col lg:flex-row lg:items-center justify-between gap-3"><div><div className="text-sm font-bold text-[var(--text-main)]">{alert.title}</div><p className="text-xs text-[var(--text-secondary)] mt-1">{alert.description}</p></div><div className="flex gap-2"><button onClick={() => onNavigate(alert.targetTab)} className="px-3 py-2 rounded-lg border border-[var(--border-color)] text-xs font-bold text-[var(--text-main)] flex items-center gap-1">Abrir área <ArrowRight className="w-3.5 h-3.5"/></button><button disabled={exists || creating === alert.id} onClick={async () => { setCreating(alert.id); try { await onCreateTask(alert.taskTitle); } finally { setCreating(null); } }} className="px-3 py-2 rounded-lg bg-[var(--blue-accent)] disabled:opacity-50 text-white text-xs font-bold">{exists ? 'Ação encaminhada' : creating === alert.id ? 'Criando...' : 'Criar tarefa'}</button></div></div>; })}</div></div>;
}
