import type { RuntimeConfigurationDefinition } from './RuntimeConfigurationTypes';

export const RUNTIME_CONFIGURATION_REGISTRY: RuntimeConfigurationDefinition[] = [
  {
    key: 'VITE_PERSISTENCE_FALLBACK_MODE',
    label: 'Política de fallback de persistência',
    description: 'Define auto, enabled ou disabled para o fallback local dos repositórios.',
    scope: 'public_client',
    requiredForProduction: true,
    category: 'database',
    targetTab: 'client_environments',
  },
  {
    key: 'VITE_APP_URL',
    label: 'URL pública da aplicação',
    description: 'URL pública usada pelo frontend para links e contexto de execução.',
    scope: 'public_client',
    requiredForProduction: true,
    category: 'application',
    targetTab: 'client_environments',
  },
  {
    key: 'DATABASE_MODE',
    label: 'Modo de persistência',
    description: 'Define se o backend opera com JSON local ou Supabase.',
    scope: 'server_only',
    requiredForProduction: true,
    category: 'database',
    targetTab: 'platform_monitoring',
  },
  {
    key: 'SUPABASE_URL',
    label: 'URL do Supabase',
    description: 'Endpoint do projeto Supabase usado pelo backend.',
    scope: 'server_only',
    requiredForProduction: true,
    category: 'database',
    targetTab: 'platform_monitoring',
  },
  {
    key: 'SUPABASE_ANON_KEY',
    label: 'Chave pública do Supabase',
    description: 'Chave anônima usada somente em fluxos autorizados pela política RLS.',
    scope: 'server_only',
    requiredForProduction: true,
    category: 'database',
    targetTab: 'platform_monitoring',
  },
  {
    key: 'SUPABASE_SERVICE_ROLE_KEY',
    label: 'Service Role do Supabase',
    description: 'Segredo exclusivo do backend. Nunca deve ser exposto ao bundle Vite.',
    scope: 'server_only',
    requiredForProduction: true,
    category: 'security',
    targetTab: 'client_environments',
  },
  {
    key: 'AI_ENCRYPTION_KEY',
    label: 'Criptografia de conexões de IA',
    description: 'Chave do backend para proteção de credenciais e conexões de IA.',
    scope: 'server_only',
    requiredForProduction: true,
    category: 'security',
    targetTab: 'client_environments',
  },
  {
    key: 'VITE_PNCP_BASE_URL',
    label: 'Base pública PNCP',
    description: 'URL pública utilizada pelo cliente/API proxy para consultas do PNCP.',
    scope: 'public_client',
    requiredForProduction: false,
    category: 'integrations',
    targetTab: 'commercial_radar',
  },
  {
    key: 'VITE_COMPRAS_GOV_BASE_URL',
    label: 'Base pública Compras.gov',
    description: 'URL pública utilizada pelo cliente/API proxy para consultas do Compras.gov.',
    scope: 'public_client',
    requiredForProduction: false,
    category: 'integrations',
    targetTab: 'commercial_radar',
  },
  {
    key: 'VITE_AI_GATEWAY_URL',
    label: 'Gateway público de IA',
    description: 'URL pública do gateway de orquestração da Beta IA.',
    scope: 'public_client',
    requiredForProduction: false,
    category: 'ai',
    targetTab: 'beta_brain',
  },
  {
    key: 'AI_GATEWAY_KEY',
    label: 'Credencial do Gateway de IA',
    description: 'Segredo exclusivo do backend para autenticação no gateway de IA.',
    scope: 'server_only',
    requiredForProduction: false,
    category: 'security',
    targetTab: 'client_environments',
  },
  {
    key: 'VITE_R2_PUBLIC_BASE_URL',
    label: 'URL pública do Cloudflare R2',
    description: 'Base pública para leitura de objetos liberados.',
    scope: 'public_client',
    requiredForProduction: false,
    category: 'storage',
    targetTab: 'client_environments',
  },
  {
    key: 'R2_ACCESS_KEY_ID',
    label: 'Access Key do Cloudflare R2',
    description: 'Identificador de acesso exclusivo do backend.',
    scope: 'server_only',
    requiredForProduction: false,
    category: 'storage',
    targetTab: 'client_environments',
  },
  {
    key: 'R2_SECRET_ACCESS_KEY',
    label: 'Secret Key do Cloudflare R2',
    description: 'Segredo exclusivo do backend para operações no R2.',
    scope: 'server_only',
    requiredForProduction: false,
    category: 'security',
    targetTab: 'client_environments',
  },
  {
    key: 'R2_BUCKET_NAME',
    label: 'Bucket do Cloudflare R2',
    description: 'Nome do bucket operacional de documentos e anexos.',
    scope: 'server_only',
    requiredForProduction: false,
    category: 'storage',
    targetTab: 'client_environments',
  },
];
